# Generated by Django 5.2.6 on 2025-09-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('TORRE', 'Torre'), ('CONDOMINIO', 'Condomínio')], max_length=20)),
                ('referencia_id', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='Gasometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gasometro', to='gascontrolproject.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('DONO', 'Dono'), ('INQUILINO', 'Inquilino'), ('MORADOR', 'Morador')], max_length=10)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='gascontrolproject.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Torres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(default='Bloco X', max_length=10)),
                ('numero', models.CharField(max_length=10)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='gascontrolproject.condominio')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='gascontrolproject.torres'),
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField()),
                ('consumo_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('SEMESTRAL', 'Semestral')], default='MENSAL', max_length=10)),
                ('gasometro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='gascontrolproject.gasometro')),
            ],
            options={
                'unique_together': {('gasometro', 'data_leitura')},
            },
        ),
    ]
