# Generated by Django 5.2.6 on 2025-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Condominio Sorgatto', max_length=20)),
                ('local', models.CharField(default='Tatuapé', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Torres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Bloco X', max_length=10)),
            ],
        ),
    ]
