# Generated by Django 5.2.6 on 2025-09-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascontrolproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torres',
            old_name='nome',
            new_name='identificacao',
        ),
        migrations.AddField(
            model_name='torres',
            name='condominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='gascontrolproject.condominio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torres',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominio',
            name='local',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='condominio',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('torre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='gascontrolproject.torres')),
            ],
        ),
    ]
