# Generated by Django 5.2.6 on 2025-09-15 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascontrolproject', '0002_rename_nome_torres_identificacao_torres_condominio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('DONO', 'Dono'), ('INQUILINO', 'Inquilino'), ('MORADOR', 'Morador')], max_length=10)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='gascontrolproject.apartamento')),
            ],
        ),
    ]
