# Generated by Django 5.2.6 on 2025-09-17 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascontrolproject', '0003_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gasometro', to='gascontrolproject.apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField()),
                ('consumo_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral')], default='MENSAL', max_length=10)),
                ('gasometro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='gascontrolproject.gasometro')),
            ],
            options={
                'unique_together': {('gasometro', 'data_leitura')},
            },
        ),
    ]
