# Generated by Django 5.2.6 on 2025-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gascontrolproject', '0004_hidrometro_leitura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('TORRE', 'Torre'), ('CONDOMINIO', 'Condomínio')], max_length=20)),
                ('referencia_id', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.AlterField(
            model_name='leitura',
            name='periodicidade',
            field=models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('BIMESTRAL', 'Bimestral'), ('SEMESTRAL', 'Semestral')], default='MENSAL', max_length=10),
        ),
    ]
