services:
  web:
    build: .
    image: gascontrolproject-web
    command: >
      sh -c "sleep 5 &&
            python manage.py migrate --noinput &&
            python manage.py collectstatic --noinput &&
            gunicorn setup.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/gascontrolproject
      - static_volume:/gascontrolproject/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-production}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"


volumes:
  postgres_data:
  static_volume: